### ISSUE TITLE
Getting crash in version 6 Marshmallow

### ISSUE THREAD

**Issue by Dhatchanamoorthy** [l0s/fernet-java8#377]
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64; 

solution - need to import android/util/Base64 instead of java. 
whether it will fixed by ur side ? or any condition i can put?

**Comment by l0s** [comment]
@Dhatchanamoorthy which methods are you using? Instead of using methods that accept and return `String`, can you use the methods that accept and return `byte[]` instead? The onus will be on you to perform the Base64 encoding and decoding. Note, you need to use the "URL and filename safe" variant of Base64.

Unfortunately, it looks like `java.util.Base64` is [not available in Android](https://developer.android.com/studio/write/java8-support-table).

**Comment by l0s** [comment]
@Dhatchanamoorthy does the byte array API work for you?

**Comment by Dhatchanamoorthy** [comment]
@l0s Im using this below function. can u help me here?
public static String fernetEncryption(String emailId,String keyString) {
        // generate a key
        Key key = new Key(keyString);
        // encrypt
        Token token = Token.generate(key, emailId);
        return token.serialise();
    }

**Comment by Dhatchanamoorthy** [comment]
@l0s getting this crash in below version 7.1 android devices 
java.lang.NoClassDefFoundError: 
  at com.macasaet.fernet.Constants.<clinit> (SourceFile:2)
  at com.macasaet.fernet.Key.<init> (SourceFile:11)

**Comment by l0s** [comment]
@Dhatchanamoorthy can you try this?

    // generate a key
    final byte[] keyBytes = Base64.decode(keyString, Base64.URL_SAFE);
    final Key key = new Key(keyBytes);
    // encrypt
    final Token token = Token.generate(key, emailId);
    final ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    token.writeTo(outputStream);
    return Base64.encodeToString(outputStream.toByteArray(), Base64.URL_SAFE);

That _should_ avoid any internal use of `java.util.Base64`.

**Comment by l0s** [comment]
@Dhatchanamoorthy I'm going to close this issue. Feel free to reopen it or create a new one if this continues to be an issue.
